export const icons = {
  ALL: require('@/assets/icons/all.png'),
  DINNER: require('@/assets/icons/dinner.png'),
  LUNCH: require('@/assets/icons/lunch.png'),
  APPETIZER: require('@/assets/icons/appetizer.png'),
  BREAKFAST: require('@/assets/icons/breakfast.png'),
  DESSERT: require('@/assets/icons/dessert.png'),
  DRINKS: require('@/assets/icons/drinks.png'),
  SNACK: require('@/assets/icons/snack.png'),
  VEGAN: require('@/assets/icons/vegan.png'),
  VEGETARIAN: require('@/assets/icons/vegetarian.png'),
  GLUTEN_FREE: require('@/assets/icons/glutenFree.png'),
  CHEF: require('@/assets/icons/002-chef.png'),
  SEARCH: require('@/assets/icons/001-search.png'),
  PLUS: require('@/assets/icons/001-plus.png'),
  BOOKMARK: require('@/assets/icons/005-save-instagram.png'),
  BOOKMARK_FULL: require('@/assets/icons/bookmark.png'),
  USER: require('@/assets/icons/004-user.png'),
  EMPTY_CHEF: require('@/assets/icons/chef-empty.png'),
  EYE_VIEW: require('@/assets/icons/view.png'),
  EYE_HIDE: require('@/assets/icons/hide.png'),
  HEART: require('@/assets/icons/001-heart.png'),
  FULL_HEART: require('@/assets/icons/heart.png'),
  CLOCK: require('@/assets/icons/003-clock.png'),
  CHAT: require('@/assets/icons/002-chat.png'),
};
